name: Build for macOS x64

permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          git submodule update --init --recursive
          chmod +x ./build.sh

      - name: Install Dependencies
        run: |
          brew install cmake ninja || true
          brew install fmt ftxui || true

      - name: Build Debug
        run: |
          ./build.sh -v debug

      - name: Build Release
        run: |
          ./build.sh -v release

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/*.zip
          if-no-files-found: warn