name: Build for macOS Legacy

permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      OSX_SDK_VERSION: "10.5"
      OSX_SDK_URL: "https://github.com/alexey-lysiuk/macos-sdk/releases/download/10.5/MacOSX10.5.tar.bz2"
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          git submodule update --init --recursive
          chmod +x ./Legacy/build.sh

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang bison flex libssl-dev libxml2-dev libbz2-dev cmake ninja build-essential xz-utils git curl || true

      - name: Install osxcross
        run: |
          git clone https://github.com/tpoechtrager/osxcross.git
          cd osxcross
          git checkout osxcross-1.1
          mkdir -p tarballs
          curl -L $OSX_SDK_URL -o tarballs/MacOSX10.5.sdk.tar.xz
          UNATTENDED=1 OSX_VERSION_MIN=$OSX_SDK_VERSION ./build.sh
          cd ..

      - name: Build
        run: |
          export PATH="${{ github.workspace }}/osxcross/target/bin:$PATH"
          ./Legacy/build.sh -v

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: Legacy/build/*.zip
          if-no-files-found: warn